version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/workspace
    ports:
      - "3000:3000"
    command: /bin/sh -c "while sleep 1000; do :; done"